services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    entrypoint: scripts/entrypoint.sh
    env_file: .env
    ports:
      - ${API_PORT}:8000
  db:
    image: postgres:16-alpine
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - fake-or-not-vol:/var/lib/postgresql/data
volumes:
  fake-or-not-vol:
