services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - fake-or-not-dev-vol:/var/lib/postgresql/data
volumes:
  fake-or-not-dev-vol:
